package main

import (
	"os"
	"sort"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

var builtinPackages []string

func main() {
	tmpl, err := template.New("a").Parse(`package gollect

// A list of Golang's builtin package paths except internal prefixed packages.
// Packages differ depending on the environment, but we ignore it
// because they are not so important in competition programming.
//
// Writing directly for better performance
// generated by cmd/list-builtin-packages
var builtinPackages = map[string]interface{}{{"{"}}{{ range . }}
	"{{ . }}": struct{}{},{{ end }}
}

func isBuiltinPackage(path string) bool {
	_, ok := builtinPackages[path]
	return ok
}
`)

	if err != nil {
		panic(err)
	}

	sort.Strings(builtinPackages)

	err = tmpl.Execute(os.Stdout, builtinPackages)
	if err != nil {
		panic(err)
	}
}

func init() {
	pkgs, err := packages.Load(nil, "std")
	if err != nil {
		panic(err)
	}

	for _, pkg := range pkgs {
		p := pkg.PkgPath
		if !strings.Contains(p, "internal/") &&
			!strings.HasPrefix(p, "vendor/") {
			builtinPackages = append(builtinPackages, p)
		}
	}
}
