name: CI
on: [push]
jobs:
  test:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Check format
        run: test -z "$(gofmt -s -l .| grep -Ev 'testdata/codes|out/')"

      - name: Test
        run: make test-ci
