name: CI
on: [push, pull_request]
jobs:
  test:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Check format
        run: test -z "$(gofmt -s -l .| grep -Ev 'testdata/(codes|cases)|out/')"

      - name: Test
        run: make ci
